default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: APP_apae_development

test:
  <<: *default
  database: APP_apae_test

production:
  <<: *default
  database: APP_apae_production
  username: APP_apae
  password: <%= ENV['APP_APAE_DATABASE_PASSWORD'] %>
